theme: jekyll-theme-hacker
title: "Ryan Fang – Game Developer Portfolio"
description: Unity Game Design and Programming
email: ryan@example.com
linkedin: https://www.linkedin.com/in/ryanfang/
itch: https://ryanfang.itch.io
github: https://github.com/ryanfang
